UPSTREAM: ASoC: qcom: Fix uninitialized symbol warning.
This patch fixes following static checker warning, by initializing the
ret to -EINVAL, as one of the code path in lpass_platform_pcm_new()
uses this variable uninitialized.

sound/soc/qcom/lpass-platform.c:555 lpass_platform_pcm_new()
error: uninitialized symbol 'ret'.

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Signed-off-by: Mark Brown <broonie@kernel.org>
cherry picked from commit ea4d25d5a3709cba0d3df2195edffc400170394f
Signed-off-by: Russ Weight <russell.h.weight@intel.com>