UPSTREAM: ASoC: kirkwood: fix build failure
While building m32r allmodconfig the build failed with:
ERROR: "bad_dma_ops" [sound/soc/kirkwood/snd-soc-kirkwood.ko] undefined!

To satisfy the dependency CONFIG_SND_KIRKWOOD_SOC should depend on
HAS_DMA.

Signed-off-by: Sudip Mukherjee <sudip.mukherjee@codethink.co.uk>
Signed-off-by: Mark Brown <broonie@kernel.org>
cherry picked from commit b01518ca88410195ace38ce755c1206588e5c167
Signed-off-by: Russ Weight <russell.h.weight@intel.com>