UPSTREAM: ASoC: atmel: fix build failure
m32r allmodconfig build is failing with the error:
ERROR: "bad_dma_ops" [sound/soc/atmel/snd-soc-atmel-pcm-pdc.ko] undefined!

The code is using DMA but the related dependency is not mentioned in the
Kconfig.

Signed-off-by: Sudip Mukherjee <sudip.mukherjee@codethink.co.uk>
Signed-off-by: Mark Brown <broonie@kernel.org>
cherry picked from commit 8d7d11005e9302fff3c50dd5193cf241ea41bba1
Signed-off-by: Russ Weight <russell.h.weight@intel.com>