UPSTREAM: ASoC: rcar: fix 'const static' variables
When building with 'make W=1', we get a harmless warning about
slightly incorrect prototypes in the rcar audio driver:

sound/soc/sh/rcar/gen.c: In function 'rsnd_gen2_probe':
sound/soc/sh/rcar/gen.c:209:2: error: 'static' is not at beginning of declaration [-Werror=old-style-declaration]

This changes the 'const static' to 'static const' as it should be.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Mark Brown <broonie@kernel.org>
cherry picked from commit cc9bdcf2a4f0cedf7b7425a54578a82bf31dd8f9
Signed-off-by: Russ Weight <russell.h.weight@intel.com>