UPSTREAM: ASoC: rk3036: fix missing dependency on REGMAP_MMIO
When SND_SOC_INNO_RK3036 is enabled but REGMAP_MMIO is not, the MODPOST
step fails with this error:

  ...
  Kernel: arch/x86/boot/bzImage is ready  (#3)
    Building modules, stage 2.
    MODPOST 3203 modules
  ERROR: "__devm_regmap_init_mmio_clk" [sound/soc/codecs/snd-soc-inno-rk3036.ko] undefined!

BUG=chrome-os-partner:50756
TEST=Build and boot on rk3288

Change-Id: Iae23023028ec9fce4ace30bf3c40d14ff4398073
Signed-off-by: Antonio Ospite <ao2@ao2.it>
Signed-off-by: Mark Brown <broonie@kernel.org>
Signed-off-by: Douglas Anderson <dianders@chromium.org>
(cherry picked from commit 7315917f7ccdf5eb5758f663a781daa7599d63d7)